ianser_base:
    resource: "@IanserBaseBundle/Resources/config/routing.yml"
    prefix:   /

ianser_buscador:
    resource: "@IanserBuscadorBundle/Resources/config/routing.yml"
    prefix:   /api

ianser_eventos:
    resource: "@IanserEventosBundle/Resources/config/routing.yml"
    prefix:   /

ianser_user:
    resource: "@IanserUserBundle/Resources/config/routing.yml"
    prefix:   /api

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

