# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:

    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    
    
    encoders:
        Ianser\UserBundle\Entity\User: { algorithm: sha512, iterations: 10}
    
    providers:
        usuario:
            entity: { class: Ianser\UserBundle\Entity\User, property: username }
        
    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        main:
            provider: usuario
            pattern: ^/*
            anonymous: ~
            form_login: ~
            remember_me:
                key: ayatsforever
                lifetime: 3600

        
    access_control:
    - { path: ^/login, role: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/registro, role: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/admin, role: ROLE_ADMIN }
    - { path: ^/api/, role: ROLE_USUARIO }