# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:

    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    
    
    encoders:
        Ianser\UserBundle\Entity\User: { algorithm: sha512, iterations: 10}
    
    providers:
        usuario:
            entity: { class: Ianser\UserBundle\Entity\User, property: username }
        
    firewalls:
        main:
            provider: usuario
            pattern: ^/
            anonymous: true
            form_login:
                login_path: portada
                check_path: /login_check
                use_referer: true
                default_target_path: redirect_login
            logout:
                path: /logout
                target: /
            remember_me:
                key: ayatsforever
                lifetime: 3600
        

        
    access_control:
    - { path: ^/registro, role: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/empresa*, role: ROLE_EMPRESA }
    - { path: ^/api, roles: [ROLE_USUARIO, ROLE_EMPRESA, ROLE_ADMIN] }
    - { path: ^/admin, role: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/*, role: IS_AUTHENTICATED_ANONYMOUSLY }
    